# Generated by Django 5.2.11 on 2026-02-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('planned_deadline', models.DateTimeField(verbose_name='Плановый дедлайн')),
                ('actual_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое завершение')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('completed', 'Выполнена'), ('overdue', 'Просрочена')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecutionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_deadline', models.DateTimeField(verbose_name='Плановый дедлайн')),
                ('actual_deadline', models.DateTimeField(verbose_name='Фактическое завершение')),
                ('delay_days', models.IntegerField(help_text='Отрицательное значение означает досрочное выполнение', verbose_name='Отклонение от дедлайна (в днях)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи статистики')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_stats', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerformanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_delay_days', models.FloatField(default=0.0, verbose_name='Среднее отклонение от дедлайна (дни)')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='Доля выполненных задач')),
                ('early_completion_rate', models.FloatField(default=0.0, verbose_name='Доля задач, выполненных раньше срока')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления статистики')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
